@url = http://localhost:5000/tokens
@token = _jUxwxb-ufdy8_uNvBSITqCI6nfDFSS2YD5fpOcjx42qIFncYlmf6g8fQ7yn3y2H2M-LfC8QwaU0RifXBTgeTg
@ref = apjKM0-snyMY8cPWkC0OQyqd8eyxkZgplf_3w7D-QjIArFrcG0GrJ2kVmqDI7beATm88cGuE413XOw_A40_4YA

POST {{url}}/auth/
Content-Type: application/json

{"username": "admin", "password": "admin123"}

###
POST {{url}}/authorize/
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{url}}/refresh/
Content-Type: application/json
Authorization: Bearer {{ref}}

###
DELETE {{url}}/revoke_all/