root: user_management_views.index
log_register: false


views:
  audits:
    routes:
      - route: ''
        name: index

      - route: 'search'
        name: search

      
        
  tokens:
    url_prefix: 'tokens'
    routes:
      - route: 'revoke_all'
        name: revoke_all
        method: DELETE

      - route: 'authorize'
        name: authorize
        method: POST

      - route: 'refresh'
        name: refresh
        method: POST

      - route: 'auth'
        name: authenticate
        method: POST
      
      - route: ''
        name: index

      - route: 'refresh'
        name: refresh
        method: POST

  users:
    routes:

      - route: ''
        # all names will be prefixed with blueprint name by default
        # this route real name will be user_management.users.index
        name: index
        # if view is omitted is defaulted to [views name].[name]
        # in this case "users.index"
        # if method is omitted will default to GET

      # a complete declaration demonstration
      - route: '<id>'
        name: show
        view: show
        method: GET
    

      - route: 'new'
        name: new

      - route: 'new'
        name: create
        method: POST

      - route: 'edit/<id>'
        name: edit

      - route: 'edit/<id>'
        name: update
        method: POST

      - route: 'destroy/<id>'
        name: destroy
        method: DELETE

  roles:
    routes:
      

      - route: ''
        name: index

      - route: '<id>'
        name: show
        view: show
        method: GET

      - route: 'new'
        name: new

      - route: ''
        name: create
        method: POST

      - route: '<id>/edit'
        name: edit

      - route: '<id>'
        name: update
        method: POST

      - route: '<id>'
        name: destroy
        method: DELETE